### ISSUE TITLE
Output:  Err: "Unsupported"

### ISSUE THREAD

**Issue by IsabelF98** [pairwise-alignment/pa-bench#2]
Hello again. I noticed that when I run a simple test job comparing Edlib, Wfa, and AstarPa I was not getting outputs in the json file for Edlib and AstarPa.  All I get is `output:{Err:"Unsupported"}`. For Wfa however it works fine. I have attached both the yaml file and json file of the test here:
[my_teest2.zip](https://github.com/pairwise-alignment/pa-bench/files/11415500/my_teest2.zip)
Thank you!

**Comment by RagnarGrootKoerkamp** [comment]
Hey,

Yeah, that's because `Edlib` and `AstarPA` only support unit cost alignment. So you have to use `{sub: 1, open: 0, extend: 1}` for those. I'll see if I can make the error slightly more specific maybe.

**Comment by IsabelF98** [comment]
Okay, I see. That worked for Edlib but I am still not getting an output for AstarPA. Any idea why that might be?

**Comment by RagnarGrootKoerkamp** [comment]
Oh right; yeah this warning definitely needs improving: A*PA only works with `trace = true`. Basically you get the trace for free, so it's kinda unfair to run it without trace.

**Comment by RagnarGrootKoerkamp** [comment]
Maybe I should just remove that limitation alltogether to simplify

**Comment by IsabelF98** [comment]
Yes, that did it. Thank you again for the help.
