### ISSUE TITLE
Building with astarpa2

### ISSUE THREAD

**Issue by jkbonfield** [pairwise-alignment/pa-bench#6]
I appreciate this is all highly experimental, so I can continue without it by commenting it out of pa-wrapper/Cargo.toml and pa-wrapper/src/lib.rs, but I'm curious how to get astarpa2 in pa-bench.

I get an error:

```
error[E0433]: failed to resolve: could not find `AstarPa2StatsAligner` in `astarpa2`
  --> pa-wrapper/src/wrappers/astarpa2.rs:28:23
   |
28 |             astarpa2::AstarPa2StatsAligner::align_with_stats(self.as_mut(), a, b);
   |                       ^^^^^^^^^^^^^^^^^^^^ could not find `AstarPa2StatsAligner` in `astarpa2`
```

I see this function isn't in the checked out copy of astarpa, but updating the commit hash in Cargo.lock can correct that.  However it still doesn't find it.  My rust knowledge is, well, nonexistant!

Don't worry if the answer is "it's not ready yet". :)  I see the commits are coming thick and fast and these things are changing just a few days ago.

The background is I've been tasked with surveying the current landscape of pairwise sequence alignment algorithms and have found both your blog posts and pa-bench an amazing resource, so a huge thank you!  You've made my work a lot easier, and after a few trials and errors I've got the Jupyter notebooks running too.  However obviously it would be nice to also add the bleeding edge to the list too.

Note I'm thinking of also looking at some really early noddy algorithms, such as EMBOSS needle or the early Miller and Myers implementations.  It may be interesting to see the historical background and how SIMD has changed things.  (I also have the banded alignment C code for https://www.sciencedirect.com/science/article/pii/019688589190017D still, from 1991.)

**Comment by RagnarGrootKoerkamp** [comment]
Hey James, thanks for your interest :)

> I appreciate this is all highly experimental,

indeed! I am in the process of wrapping the A*PA2 paper.

> so I can continue without it by commenting it out of pa-wrapper/Cargo.toml and pa-wrapper/src/lib.rs, but I'm curious how to get astarpa2 in pa-bench.
> 
> I get an error:
> 
> ```
> error[E0433]: failed to resolve: could not find `AstarPa2StatsAligner` in `astarpa2`
>   --> pa-wrapper/src/wrappers/astarpa2.rs:28:23
>    |
> 28 |             astarpa2::AstarPa2StatsAligner::align_with_stats(self.as_mut(), a, b);
>    |                       ^^^^^^^^^^^^^^^^^^^^ could not find `AstarPa2StatsAligner` in `astarpa2`
> ```
> 
> I see this function isn't in the checked out copy of astarpa, but updating the commit hash in Cargo.lock can correct that. However it still doesn't find it. My rust knowledge is, well, nonexistant!

Ahhh, I see have a bunch of unpushed local changed, including the delayed update to the `Cargo.lock`. Just pushed and should work now!

You may also need to update to the most recent nightly release if there are still errors, `rustup update`.

> 
> Don't worry if the answer is "it's not ready yet". :) I see the commits are coming thick and fast and these things are changing just a few days ago.

I just finished the final experiments, so all should definitely work now.

> 
> The background is I've been tasked with surveying the current landscape of pairwise sequence alignment algorithms 
> and have found both your blog posts and pa-bench an amazing resource, so a huge thank you! You've made my work a lot easier, 

Indeed a lot of time went into making those blogposts, especially the [big overview](https://curiouscoding.nl/posts/pairwise-alignment/), but the time investment to actually make a paper is so much larger still. If a paper is your goal, I would be happy to collaborate!

> and after a few trials and errors I've got the Jupyter notebooks running too.

Oh that's very nice to hear !

> However obviously it would be nice to also add the bleeding edge to the list too.
> 
> Note I'm thinking of also looking at some really early noddy algorithms, such as EMBOSS needle or the early Miller and Myers implementations. It may be interesting to see the historical background and how SIMD has changed things. (I also have the banded alignment C code for https://www.sciencedirect.com/science/article/pii/019688589190017D still, from 1991.)

We could totally wrap older implementations as well. It's not that hard to generate and use rust bindings, see e.g. https://github.com/pairwise-alignment/ksw2-sys.


Looking forward to hear back from you!

**Comment by jkbonfield** [comment]
Don't worry - I'm not looking for gazump you and steal your thunder on a paper.  I wish you luck in getting yours out.  It's an update for an existing grant, with feedback required at various stages.  (Edit: also thanks for the "big overview".  I'd already been looking at that - very useful and impressively detailed.  Thank you!)

I'll try again with the build.  Thanks.

**Comment by RagnarGrootKoerkamp** [comment]
> Don't worry - I'm not looking for gazump you and steal your thunder on a paper.

It's more like, there's too much to do and I have too little time to ever get a review paper going by myself. A collaboration could be  a good way to actually get it done :)

> I wish you luck in getting yours out. It's an update for an existing grant, with feedback required at various stages. (Edit: also thanks for the "big overview". I'd already been looking at that - very useful and impressively detailed. Thank you!)

Oh actually if you also care about string searching methods in general and schemes more general than only edit distance, there's also this list: https://curiouscoding.nl/notes/bitpacking/. (Even more daunting than the other table :/ )

> 
> I'll try again with the build. Thanks.

:+1:

**Comment by jkbonfield** [comment]
I can confirm it's building fine for me now without needing local modifications.
Many thanks for the speedy response.
